version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gastosDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  backend:
    image: ddelgadoi/backend-ups
    container_name: backend
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db  
      - DB_PORT=5432
      - DB_NAME=gastosDB
    ports:
      - "3000:3000"
    depends_on:
      - db



  frontend:
    image: ddelgadoi/frontend-ups
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: